// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Petter André Sjulstad
//
// Fork-fidelity CONFORMANCE matrix (phase 1E). The exact fidelity a fork of one
// agent into another achieves is determined by two capability flags — this
// derives, for every (source -> destination) pair, the tier the fork will land
// at, so the runtime support matrix can be GENERATED and regression-tested
// instead of hand-maintained (and silently drifting from the code).
//
// The tier logic here MUST mirror resolveForkFidelity in ./fork.ts — a test
// (test/fork-matrix.test.ts) drives representative pairs through the real
// resolveForkFidelity and asserts they agree, so this can't drift from the
// production decision path.

export type ForkTier = "full" | "replayed" | "seeded";

/** The two capability flags that decide fork fidelity for an agent. */
export interface AgentForkCaps {
  id: string;
  displayName?: string;
  /** Same-runtime byte-exact native transport (export/importForFork). */
  forkTransport?: boolean;
  /** Cross-runtime portable-history import (importHistoryForFork). */
  forkHistoryImport?: boolean;
}

/**
 * Tier a fork of `source` into `dest` achieves:
 *   - "full"     same runtime, both ends speak native transport (byte-exact);
 *   - "replayed" the destination can import portable history (true cross-agent
 *                fork onto a copy of the transcript);
 *   - "seeded"   otherwise (a continuation prompt).
 * Mirrors resolveForkFidelity: a native payload is only captured when the SOURCE
 * has forkTransport and is only importable by the SAME runtime, so "full" ⇔
 * same id AND both forkTransport.
 */
export function forkTier(source: AgentForkCaps, dest: AgentForkCaps): ForkTier {
  if (source.id === dest.id && source.forkTransport && dest.forkTransport) return "full";
  if (dest.forkHistoryImport) return "replayed";
  return "seeded";
}

export interface ForkMatrixCell {
  source: string;
  dest: string;
  tier: ForkTier;
}

/** Every ordered (source, dest) pair and its tier. */
export function forkMatrix(agents: AgentForkCaps[]): ForkMatrixCell[] {
  const cells: ForkMatrixCell[] = [];
  for (const source of agents) {
    for (const dest of agents) {
      cells.push({ source: source.id, dest: dest.id, tier: forkTier(source, dest) });
    }
  }
  return cells;
}

const TIER_MARK: Record<ForkTier, string> = { full: "●", replayed: "◑", seeded: "○" };

/** Render the matrix as a GitHub-flavored markdown table (rows = source,
 *  columns = destination), with a legend. */
export function renderForkMatrixMarkdown(agents: AgentForkCaps[]): string {
  const name = (a: AgentForkCaps) => a.displayName ?? a.id;
  const header = ["source ↓ / dest →", ...agents.map(name)].join(" | ");
  const sep = ["---", ...agents.map(() => ":-:")].join(" | ");
  const rows = agents.map((source) => {
    const cells = agents.map((dest) => TIER_MARK[forkTier(source, dest)]);
    return [name(source), ...cells].join(" | ");
  });
  return [
    "<!-- GENERATED by scripts/gen-fork-matrix.ts — do not edit by hand. -->",
    "# Fork fidelity matrix",
    "",
    "Legend: ● full (byte-exact, same runtime) · ◑ replayed (portable history) · ○ seeded (continuation prompt).",
    "",
    `| ${header} |`,
    `| ${sep} |`,
    ...rows.map((r) => `| ${r} |`),
    "",
  ].join("\n");
}
