#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Petter André Sjulstad
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { currentBivyVersion } from "./app-version.js";
import { defaultDataDir } from "./data-dir.js";
import { checkPluginCompatibility, doctorPluginManifest, recommendedBivyRange, type PluginManifest } from "./plugin-sdk/index.js";
import { installPlugin, installedAgentContributions, listInstalledPlugins, pluginStoreDir, readPluginManifest, removePlugin } from "./plugins/store.js";

function usage(exitCode = 0): never {
  console.log(`Usage: bivy plugin <command> [options]

Develop, install, and inspect declarative Bivy plugins.

Commands:
  init [directory]         Scaffold a plugin manifest
  validate <path>          Validate a bivy.plugin.yaml/json manifest
  doctor <path>            Check compatibility and adapter executables
  test <path>              Run static checks and live ACP handshakes
  install <path> [--force] Install into this node's plugin store
  list [--json]            List installed plugins and diagnostics
  remove <id>              Remove an installed plugin

Options:
  --adapter <acp|process>  Adapter generated by init (default: acp)
  --id <slug>              Plugin id generated by init
  --name <name>            Display name generated by init
  --json                   Emit machine-readable JSON
  --force                  Replace an installed plugin with the same id

Plugin test never prompts a process adapter: that could spend money or mutate a
workspace. It verifies the executable and static contract. ACP adapters must
complete initialize and session/new through Bivy's real bridge.`);
  process.exit(exitCode);
}

function outputJson(value: unknown): void {
  console.log(JSON.stringify(value, null, 2));
}

function option(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : undefined;
}

function positionalArgs(args: string[]): string[] {
  const valued = new Set(["--adapter", "--id", "--name"]);
  const out: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index]!;
    if (valued.has(arg)) { index += 1; continue; }
    if (!arg.startsWith("-")) out.push(arg);
  }
  return out;
}

function agentConflictDiagnostics(dataDir: string): string[] {
  const installed = installedAgentContributions(dataDir);
  const errors = [...installed.errors];
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const reserved = new Set<string>([
    "pi", "claude", "claude-code", "claude-code-sdk", "generic-cli", "codex-approvals",
    "openclaw", "bivy-agent-protocol", "acp", "openhands", "swe-agent",
    "openai-agents-sdk", "langgraph", "google-adk", "autogen", "crew-ai",
  ]);
  try {
    const builtins = JSON.parse(fs.readFileSync(path.join(root, "bin", "agent-manifest.json"), "utf8"));
    for (const agent of builtins?.agents ?? []) if (typeof agent?.id === "string") reserved.add(agent.id);
  } catch { /* diagnosed by `bivy agents`; retain native ids */ }
  const configured = new Set<string>();
  try {
    const custom = JSON.parse(process.env.BIVY_CUSTOM_AGENTS ?? "[]");
    for (const agent of Array.isArray(custom) ? custom : []) if (typeof agent?.id === "string") configured.add(agent.id.toLowerCase());
  } catch { /* diagnosed by config validation */ }
  for (const contribution of installed.agents) {
    const id = contribution.agent.id;
    if (reserved.has(id)) errors.push(`${contribution.pluginId}: agent id ${id} conflicts with a built-in runtime`);
    else if (configured.has(id)) errors.push(`${contribution.pluginId}: agent id ${id} conflicts with node configuration`);
  }
  return errors;
}

function fail(error: unknown, json: boolean): never {
  const message = error instanceof Error ? error.message : String(error);
  if (json) outputJson({ ok: false, error: message });
  else console.error(`error: ${message}`);
  process.exit(1);
}

function scaffold(args: string[], json: boolean): void {
  const positional = positionalArgs(args);
  const directory = path.resolve(positional[0] ?? ".");
  const inferred = path.basename(directory).toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
  const id = (option(args, "--id") ?? inferred).toLowerCase();
  if (!/^[a-z][a-z0-9-]{1,47}$/.test(id)) throw new Error("Use --id with a lowercase slug of 2-48 characters");
  const adapter = option(args, "--adapter") ?? "acp";
  if (adapter !== "acp" && adapter !== "process") throw new Error("--adapter must be acp or process");
  const name = option(args, "--name") ?? id.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ");
  const file = path.join(directory, "bivy.plugin.yaml");
  if (fs.existsSync(file)) throw new Error(`${file} already exists`);
  fs.mkdirSync(directory, { recursive: true });
  const manifest = `# yaml-language-server: $schema=https://raw.githubusercontent.com/bivysh/bivy/main/packages/plugin-sdk/schema/bivy.plugin.schema.json
apiVersion: bivy.sh/v1alpha1
kind: Plugin
metadata:
  id: ${id}
  name: ${JSON.stringify(name)}
  version: 0.1.0
requires:
  bivy: ${JSON.stringify(recommendedBivyRange(currentBivyVersion()))}
contributes:
  agents:
    - id: ${id}
      name: ${JSON.stringify(name)}
      authOwner: agent
      adapter:
        kind: ${adapter}
        command: ${id}
${adapter === "process" ? "        promptMode: stdin\n" : "        args: [acp]\n"}`;
  fs.writeFileSync(file, manifest, { flag: "wx", mode: 0o644 });
  const body = { ok: true, directory, manifest: file, plugin: { id, name, adapter } };
  if (json) outputJson(body);
  else {
    console.log(`Created ${file}`);
    console.log(`Next: set the adapter command, then run 'bivy plugin doctor ${directory}' and 'bivy plugin test ${directory}'.`);
  }
}

function manifestSummary(file: string, manifest: PluginManifest): Record<string, unknown> {
  return {
    ok: true,
    file,
    plugin: { id: manifest.metadata.id, name: manifest.metadata.name, version: manifest.metadata.version },
    compatibility: checkPluginCompatibility(manifest, currentBivyVersion()),
    contributions: { agents: manifest.contributes.agents.map((agent) => ({ id: agent.id, adapter: agent.adapter.kind })) },
  };
}

async function testPlugin(input: string): Promise<{ ok: boolean; file: string; checks: unknown[]; errors: string[]; warnings: string[] }> {
  const { file, manifest } = readPluginManifest(input);
  const diagnosis = doctorPluginManifest(manifest, { bivyVersion: currentBivyVersion(), cwd: path.dirname(file) });
  const checks: Array<{ name: string; status: "pass" | "warning" | "fail"; message: string; agentId?: string }> = [...diagnosis.checks];
  const errors = [...diagnosis.errors];
  if (!diagnosis.ok) return { ok: false, file, checks, errors, warnings: diagnosis.warnings };

  const temp = fs.mkdtempSync(path.join(os.tmpdir(), "bivy-plugin-test-"));
  const previousDir = process.env.BIVY_PLUGIN_DIR;
  process.env.BIVY_PLUGIN_DIR = path.join(temp, "plugins");
  try {
    installPlugin(file, { dataDir: temp, bivyVersion: currentBivyVersion() });
    const runtimeModule = await import("./runtime/index.js");
    const conflicts = runtimeModule.pluginAgentConflictDiagnostics();
    if (conflicts.length) errors.push(...conflicts);
    if (!errors.length) {
      for (const agent of manifest.contributes.agents) {
        if (agent.adapter.kind === "process") {
          checks.push({ name: "conformance", agentId: agent.id, status: "pass", message: "Static process-adapter conformance passed" });
          continue;
        }
        let session: { dispose(): void } | undefined;
        let timer: NodeJS.Timeout | undefined;
        try {
          const runtime = runtimeModule.makeRuntime({
            runtime: agent.id,
            credsDir: path.join(temp, "credentials"),
            piDir: path.join(temp, "pi"),
            sessionsDir: path.join(temp, "sessions"),
          });
          await Promise.race([
            (async () => {
              const opened = await runtime.createSession({ workspace: path.dirname(file) });
              session = opened.session;
              const open = (opened.session as unknown as { open?: () => Promise<void> }).open;
              if (typeof open !== "function") throw new Error("ACP runtime does not expose the conformance handshake");
              await open.call(opened.session);
            })(),
            new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error("ACP handshake timed out after 15 seconds")), 15_000); }),
          ]);
          checks.push({ name: "conformance", agentId: agent.id, status: "pass", message: "ACP initialize and session/new handshake passed" });
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          errors.push(`${agent.id}: ${message}`);
          checks.push({ name: "conformance", agentId: agent.id, status: "fail", message });
        } finally {
          if (timer) clearTimeout(timer);
          session?.dispose();
        }
      }
    }
  } finally {
    if (previousDir === undefined) delete process.env.BIVY_PLUGIN_DIR;
    else process.env.BIVY_PLUGIN_DIR = previousDir;
    fs.rmSync(temp, { recursive: true, force: true });
  }
  return { ok: errors.length === 0, file, checks, errors, warnings: diagnosis.warnings };
}

export async function main(argv = process.argv.slice(2)): Promise<void> {
  const [command, ...args] = argv;
  if (!command || command === "help" || command === "--help" || command === "-h" || args.includes("--help") || args.includes("-h")) usage();
  const json = args.includes("--json");
  const positional = positionalArgs(args);
  const dataDir = defaultDataDir();

  try {
    if (command === "init") {
      scaffold(args, json);
      return;
    }

    if (command === "validate") {
      const input = positional[0];
      if (!input) fail("Usage: bivy plugin validate <path>", json);
      const { file, manifest } = readPluginManifest(input);
      const result = manifestSummary(file, manifest);
      if (json) outputJson(result);
      else {
        console.log(`Valid plugin: ${manifest.metadata.name} (${manifest.metadata.id}@${manifest.metadata.version})`);
        console.log((result.compatibility as { message: string }).message);
        console.log(`Agents: ${manifest.contributes.agents.map((agent) => `${agent.id} [${agent.adapter.kind}]`).join(", ")}`);
      }
      return;
    }

    if (command === "doctor") {
      const input = positional[0];
      if (!input) fail("Usage: bivy plugin doctor <path>", json);
      const { file, manifest } = readPluginManifest(input);
      const result = doctorPluginManifest(manifest, { bivyVersion: currentBivyVersion(), cwd: path.dirname(file) });
      const body = { ...result, file, plugin: manifest.metadata.id };
      if (json) outputJson(body);
      else {
        for (const check of result.checks) console.log(`${check.status === "pass" ? "✓" : check.status === "warning" ? "!" : "✗"} ${check.name}${check.agentId ? ` (${check.agentId})` : ""}: ${check.message}`);
      }
      if (!result.ok) process.exitCode = 1;
      return;
    }

    if (command === "test") {
      const input = positional[0];
      if (!input) fail("Usage: bivy plugin test <path>", json);
      const body = await testPlugin(input);
      if (json) outputJson(body);
      else {
        for (const check of body.checks as Array<{ status: string; name: string; agentId?: string; message: string }>) console.log(`${check.status === "pass" ? "✓" : check.status === "warning" ? "!" : "✗"} ${check.name}${check.agentId ? ` (${check.agentId})` : ""}: ${check.message}`);
        for (const error of body.errors) console.error(`error: ${error}`);
      }
      if (!body.ok) process.exitCode = 1;
      return;
    }

    if (command === "install" || command === "add") {
      const input = positional[0];
      if (!input) fail("Usage: bivy plugin install <path> [--force]", json);
      const result = installPlugin(input, { dataDir, force: args.includes("--force") });
      const body = { ok: true, installed: result.manifest.metadata.id, version: result.manifest.metadata.version, path: result.path, replaced: result.replaced, restartRequired: true };
      if (json) outputJson(body);
      else {
        console.log(`${result.replaced ? "Updated" : "Installed"} ${result.manifest.metadata.name} (${result.manifest.metadata.id}@${result.manifest.metadata.version}).`);
        console.log(`Stored at ${result.path}`);
        console.log("Restart Bivy to activate it: bivy restart");
      }
      return;
    }

    if (command === "list" || command === "ls") {
      const plugins = listInstalledPlugins(dataDir);
      const conflicts = agentConflictDiagnostics(dataDir);
      const body = {
        ok: conflicts.length === 0 && plugins.every((plugin) => plugin.errors.length === 0),
        directory: pluginStoreDir(dataDir),
        plugins: plugins.map((plugin) => ({
          id: plugin.id,
          name: plugin.manifest?.metadata.name,
          version: plugin.manifest?.metadata.version,
          agents: plugin.manifest?.contributes.agents.map((agent) => ({ id: agent.id, adapter: agent.adapter.kind })) ?? [],
          status: plugin.errors.length ? "invalid" : "installed",
          errors: plugin.errors,
        })),
        errors: conflicts,
      };
      if (json) outputJson(body);
      else if (!plugins.length) console.log(`No plugins installed. Store: ${body.directory}`);
      else {
        console.log(`Plugins (${body.directory})`);
        for (const plugin of body.plugins) {
          const detail = plugin.status === "installed"
            ? `${plugin.name} ${plugin.version} · ${plugin.agents.map((agent) => `${agent.id} [${agent.adapter}]`).join(", ")}`
            : `invalid · ${plugin.errors.join("; ")}`;
          console.log(`  ${plugin.id}: ${detail}`);
        }
        for (const error of body.errors) console.error(`  warning: ${error}`);
      }
      if (!body.ok) process.exitCode = 1;
      return;
    }

    if (command === "remove" || command === "rm" || command === "uninstall") {
      const id = positional[0];
      if (!id) fail("Usage: bivy plugin remove <id>", json);
      const removed = removePlugin(id, dataDir);
      if (!removed) fail(`Plugin ${id} is not installed`, json);
      const body = { ok: true, removed: id, restartRequired: true };
      if (json) outputJson(body);
      else {
        console.log(`Removed plugin ${id}.`);
        console.log("Restart Bivy to unload it: bivy restart");
      }
      return;
    }

    usage(1);
  } catch (error) {
    fail(error, json);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
